/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/subscriptions": {
    /** Create subscription */
    post: operations["createSubscription"];
  };
  "/api/subscriptions/{id}": {
    /** Remove subscription */
    delete: operations["deleteSubscription"];
  };
  "/api/studies": {
    /** List studies */
    get: operations["listStudies"];
    /** Create study */
    post: operations["createStudy"];
  };
  "/api/studies/{id}": {
    /** Get study by id */
    get: operations["getStudy"];
  };
  "/api/invitations/launch": {
    /** Launch invitations */
    post: operations["launchInvitations"];
  };
  "/api/export/invitations.csv": {
    /** Export invitations CSV */
    get: operations["exportInvitations"];
  };
  "/api/profile": {
    /** Get profile */
    get: operations["getProfile"];
    /** Update profile */
    put: operations["updateProfile"];
  };
  "/api/prescreen": {
    /** Get prescreen blocks */
    get: operations["getPrescreen"];
  };
  "/api/prescreen/{id}": {
    /** Update prescreen block */
    put: operations["updatePrescreenBlock"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    SubscriptionKeysDto: {
      p256dh: string;
      auth: string;
    };
    CreateSubscriptionDto: {
      endpoint: string;
      keys: components["schemas"]["SubscriptionKeysDto"];
    };
    SubscriptionDto: components["schemas"]["CreateSubscriptionDto"] & {
      id: string;
    };
    CreateStudyDto: {
      title: string;
      description?: string;
    };
    StudyDto: components["schemas"]["CreateStudyDto"] & {
      id: string;
    };
    LaunchInvitationDto: {
      studyId: string;
      segment?: string;
      quota?: number;
    };
    LaunchInvitationResponseDto: {
      launched: number;
    };
    ProfileDto: {
      name: string;
      age: number;
      gender: string;
      city: string;
      profession: string;
      contacts: string;
    };
    UpdateProfileDto: {
      name?: string;
      age?: number;
      gender?: string;
      city?: string;
      profession?: string;
      contacts?: string;
    };
    PrescreenBlockDto: {
      id: string;
      question: string;
      answer: string;
    };
    UpdatePrescreenBlockDto: {
      answer: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Create subscription */
  createSubscription: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateSubscriptionDto"];
      };
    };
    responses: {
      /** @description Subscription created */
      201: {
        content: {
          "application/json": components["schemas"]["SubscriptionDto"];
        };
      };
    };
  };
  /** Remove subscription */
  deleteSubscription: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Deleted */
      204: {
        content: never;
      };
    };
  };
  /** List studies */
  listStudies: {
    responses: {
      /** @description Array of studies */
      200: {
        content: {
          "application/json": components["schemas"]["StudyDto"][];
        };
      };
    };
  };
  /** Create study */
  createStudy: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateStudyDto"];
      };
    };
    responses: {
      /** @description Study created */
      201: {
        content: {
          "application/json": components["schemas"]["StudyDto"];
        };
      };
    };
  };
  /** Get study by id */
  getStudy: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Study */
      200: {
        content: {
          "application/json": components["schemas"]["StudyDto"];
        };
      };
    };
  };
  /** Launch invitations */
  launchInvitations: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LaunchInvitationDto"];
      };
    };
    responses: {
      /** @description Result */
      200: {
        content: {
          "application/json": components["schemas"]["LaunchInvitationResponseDto"];
        };
      };
    };
  };
  /** Export invitations CSV */
  exportInvitations: {
    responses: {
      /** @description CSV data */
      200: {
        content: {
          "text/csv": string;
        };
      };
    };
  };
  /** Get profile */
  getProfile: {
    responses: {
      /** @description Profile */
      200: {
        content: {
          "application/json": components["schemas"]["ProfileDto"];
        };
      };
    };
  };
  /** Update profile */
  updateProfile: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateProfileDto"];
      };
    };
    responses: {
      /** @description Profile */
      200: {
        content: {
          "application/json": components["schemas"]["ProfileDto"];
        };
      };
    };
  };
  /** Get prescreen blocks */
  getPrescreen: {
    responses: {
      /** @description Array of prescreen blocks */
      200: {
        content: {
          "application/json": components["schemas"]["PrescreenBlockDto"][];
        };
      };
    };
  };
  /** Update prescreen block */
  updatePrescreenBlock: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdatePrescreenBlockDto"];
      };
    };
    responses: {
      /** @description Prescreen block */
      200: {
        content: {
          "application/json": components["schemas"]["PrescreenBlockDto"];
        };
      };
    };
  };
}
