/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/subscriptions": {
    /** Create subscription */
    post: operations["createSubscription"];
  };
  "/api/subscriptions/{id}": {
    /** Remove subscription */
    delete: operations["deleteSubscription"];
  };
  "/api/studies": {
    /** List studies */
    get: operations["listStudies"];
    /** Create study */
    post: operations["createStudy"];
  };
  "/api/studies/{id}": {
    /** Get study by id */
    get: operations["getStudy"];
  };
  "/api/invitations/launch": {
    /** Launch invitations */
    post: operations["launchInvitations"];
  };
  "/api/export/invitations.csv": {
    /** Export invitations CSV */
    get: operations["exportInvitations"];
  };
  "/api/audience": {
    /** Search audience */
    get: operations["searchAudience"];
  };
  "/api/segments": {
    /** List segments */
    get: operations["listSegments"];
    /** Create segment */
    post: operations["createSegment"];
  };
  "/api/segments/{id}/export": {
    /** Export segment CSV */
    get: operations["exportSegment"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    SubscriptionKeysDto: {
      p256dh: string;
      auth: string;
    };
    CreateSubscriptionDto: {
      endpoint: string;
      keys: components["schemas"]["SubscriptionKeysDto"];
    };
    SubscriptionDto: components["schemas"]["CreateSubscriptionDto"] & {
      id: string;
    };
    CreateStudyDto: {
      title: string;
      description?: string;
    };
    StudyDto: components["schemas"]["CreateStudyDto"] & {
      id: string;
    };
    LaunchInvitationDto: {
      studyId: string;
      segment?: string;
      quota?: number;
    };
    LaunchInvitationResponseDto: {
      launched: number;
    };
    ParticipantDto: {
      id: string;
      attributes?: {
        [key: string]: string;
      };
      prescreen?: {
        [key: string]: string;
      };
    };
    CreateSegmentDto: {
      name: string;
      filters: {
        [key: string]: string;
      };
    };
    SegmentDto: components["schemas"]["CreateSegmentDto"] & {
      id: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Create subscription */
  createSubscription: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateSubscriptionDto"];
      };
    };
    responses: {
      /** @description Subscription created */
      201: {
        content: {
          "application/json": components["schemas"]["SubscriptionDto"];
        };
      };
    };
  };
  /** Remove subscription */
  deleteSubscription: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Deleted */
      204: {
        content: never;
      };
    };
  };
  /** List studies */
  listStudies: {
    responses: {
      /** @description Array of studies */
      200: {
        content: {
          "application/json": components["schemas"]["StudyDto"][];
        };
      };
    };
  };
  /** Create study */
  createStudy: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateStudyDto"];
      };
    };
    responses: {
      /** @description Study created */
      201: {
        content: {
          "application/json": components["schemas"]["StudyDto"];
        };
      };
    };
  };
  /** Get study by id */
  getStudy: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Study */
      200: {
        content: {
          "application/json": components["schemas"]["StudyDto"];
        };
      };
    };
  };
  /** Launch invitations */
  launchInvitations: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LaunchInvitationDto"];
      };
    };
    responses: {
      /** @description Result */
      200: {
        content: {
          "application/json": components["schemas"]["LaunchInvitationResponseDto"];
        };
      };
    };
  };
  /** Export invitations CSV */
  exportInvitations: {
    responses: {
      /** @description CSV data */
      200: {
        content: {
          "text/csv": string;
        };
      };
    };
  };
  /** Search audience */
  searchAudience: {
    parameters: {
      query?: {
        attr?: string;
        value?: string;
      };
    };
    responses: {
      /** @description Array of participants */
      200: {
        content: {
          "application/json": components["schemas"]["ParticipantDto"][];
        };
      };
    };
  };
  /** List segments */
  listSegments: {
    responses: {
      /** @description Array of segments */
      200: {
        content: {
          "application/json": components["schemas"]["SegmentDto"][];
        };
      };
    };
  };
  /** Create segment */
  createSegment: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateSegmentDto"];
      };
    };
    responses: {
      /** @description Segment created */
      201: {
        content: {
          "application/json": components["schemas"]["SegmentDto"];
        };
      };
    };
  };
  /** Export segment CSV */
  exportSegment: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description CSV data */
      200: {
        content: {
          "text/csv": string;
        };
      };
    };
  };
}
