name: Lighthouse

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
        continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run build -w apps/web
      - name: Lighthouse CI
        uses: treosh/lighthouse-ci-action@v10
        env:
          LHCI_GITHUB_TOKEN: ${{ secrets.LHCI_GITHUB_TOKEN }}
        with:
          config: |
            {
              "ci": {
                "collect": { "staticDistDir": "apps/web/dist" },
                "assert": {
                  "assertions": {
                    "categories:pwa": ["error", { "minScore": 0.9 }],
                    "categories:performance": ["error", { "minScore": 0.9 }],
                    "categories:best-practices": ["error", { "minScore": 0.9 }],
                    "categories:accessibility": ["error", { "minScore": 0.9 }]
                  }
                }
              }
            }
          uploadArtifacts: true
          temporaryPublicStorage: true
