name: Deploy PWA to GitHub Pages
on:
  push:
    branches: [ main ]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build --workspace apps/web
      - run: cp apps/web/dist/index.html apps/web/dist/404.html
      - run: touch apps/web/dist/.nojekyll
      - uses: actions/upload-pages-artifact@v3
        with:
          path: apps/web/dist
    deploy:
        runs-on: ubuntu-latest
        needs: build
          environment:
              name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
          steps:
              - id: deployment
        uses: actions/deploy-pages@v4
